name: my_app
description: Clean Architecture Flutter App with BLoC, Repository, Factory, Singleton
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3

  # Dependency Injection
  get_it: ^7.6.4

  # Equatable (для удобных сравнений в BLoC)
  equatable: ^2.0.5

  # (опционально) HTTP если добавишь реальный API
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking
  mocktail: ^1.0.3

  # Integration testing
  integration_test:
    sdk: flutter

  # Линтеры (очень рекомендуется)
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
